version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run dummy test
          command: echo "No tests configured, passing step"

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "${SSH_KEY_FINGERPRINT}"
      - run:
          name: Setup SSH config
          command: |
            mkdir -p ~/.ssh
            echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
            chmod 600 ~/.ssh/config
      - run:
          name: Deploy to AWS EC2
          command: |
            ssh ubuntu@${EC2_IP_ADDRESS} 'bash -s' < ./deploy.sh

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main